repo = 'Shougo/dein.vim'

# on server stopped
# # deoplete
# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# hook_add = '''
#    let g:deoplete#enable_at_startup = 1
#    let g:deoplete#enable_ignore_case = 1
#    let g:deoplete#enable_smart_case = 1
# '''
# # deoplete on vim requires plugin 1/2
# [[plugins]]
# repo = 'roxma/nvim-yarp'
# 
# # deoplete on vim requires plugin 2/2
# [[plugins]]
# repo = 'roxma/vim-hug-neovim-rpc'
# 
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
'''
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
map <silent><C-n> :NERDTreeTabsToggle<CR>
let NERDTreeShowHidden = 1
let g:nerdtree_tabs_open_on_console_startup=0
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''
[[plugins]] # カラースキーム
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'whatyouhide/vim-gotham'
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]] # 置換のプレビュー
repo = 'markonm/traces.vim'
[[plugins]] # 囲いの便利なやつ
repo = 'tpope/vim-surround'
# Created by haya14busa -----------------------
[[plugins]] # 簡単に移動するやつ
repo = 'easymotion/vim-easymotion'
hook_add = '''
let mapleader = "\<Space>"
map <Leader> <Plug>(easymotion-prefix)
let g:EasyMotion_do_mapping = 0
nmap s <Plug>(easymotion-overwin-f2)
let g:EasyMotion_smartcase = 1 
nmap <Leader>w <Plug>(easymotion-overwin-w)
nmap <Leader>j <Plug>(easymotion-j)
nmap <Leader>k <Plug>(easymotion-k)
'''
[[plugins]] # 検索をリッチに
repo = 'haya14busa/incsearch.vim'
[[plugins]] # incsearch + easymotion
repo = 'haya14busa/incsearch-easymotion.vim'
hook_add = '''
function! s:incsearch_config(...) abort
  return incsearch#util#deepextend(deepcopy({
  \   'modules': [incsearch#config#easymotion#module({'overwin': 1})],
  \   'keymap': {
  \     "\<CR>": '<Over>(easymotion)'
  \   },
  \   'is_expr': 0
  \ }), get(a:, 1, {}))
endfunction
noremap <silent><expr> /  incsearch#go(<SID>incsearch_config())
noremap <silent><expr> ?  incsearch#go(<SID>incsearch_config({'command': '?'}))
noremap <silent><expr> g/ incsearch#go(<SID>incsearch_config({'is_stay': 1}))
'''
# ---------------------------------------------
[[plugins]] # tmuxと一緒のキーで画面移動
repo = 'christoomey/vim-tmux-navigator'
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_vert_resize = 1
let g:winresizer_horiz_resize = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
'''

# for getting git branch in airline 
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'ryanoasis/nerd-fonts'
 
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:webdevicons_enable = 1
'''

#let g:airline_theme = 'base16_ashes'
#let g:airline_theme = 'base16_bright'
#base16_default
#let g:airline_theme = 'base16_eighties'
#let g:airline_theme = 'deus'
#let g:airline_theme = 'night_owl'
#let g:airline_theme = 'violet'
#let g:airline_theme = 'tomorrow'
#let g:airline_theme = 'molokai'
#onedarl

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
let g:shades_of_purple_airline = 1
let g:airline_theme='shades_of_purple'
let g:airline#extensions#tabline#enabled = 1
let g:airline_left_sep=''
let g:airline#extensions#tabline#buffer_idx_format = {
    \ '0': '0 ',
    \ '1': '1 ',
    \ '2': '2 ',
    \ '3': '3 ',
    \ '4': '4 ',
    \ '5': '5 ',
    \ '6': '6 ',
    \ '7': '7 ',
    \ '8': '8 ',
    \ '9': '9 '
    \}
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
'''

# # [[plugins]]
# # repo = 'reireias/vim-cheatsheet'

# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Rigellute/shades-of-purple.vim'
hook_add = '''
let g:shades_of_purple_airline = 1
let g:airline_theme='shades_of_purple'
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'powerline/powerline'
# [[plugins]]
# repo = 'itchyny/lightline.vim'
# hook_add = '''
# let g:lightline = {
#     \ 'colorscheme': 'Tomorrow_Night_Blue'
#     \ }
# '''


    #\ 'colorscheme': 'ayu_mirage'
    #\ 'colorscheme': 'molokai'
    #\ 'colorscheme': 'one'
    #\ 'colorscheme': 'PaperColor'
    #\ 'colorscheme': 'material'
#[[lugins]]
#repo = '~/vim-pseudoclipboard'
# [[plugins]] # codeを検索...? (保留)
# repo = 'mileszs/ack.vim

# 個人用
#[[plugins]]
#repo = 'guns/xterm-color-table.vim'

#[[plugins]]
#repo = 'tpope/vim-fugitive'
#
#[[plugins]]
#repo = 'airblade/vim-gitgutter'
#hook_add = '''
#let g:gitgutter_highlight_lines = 1
#'''
#

